baseURL = "/"
languageCode = "cs-cz"
title = "Anonymní Přejídači (OA)"
theme = "kube"
description = "Anonymní Přejídači (OA) je společenství žen a mužů, kteří spolu sdílejí své zkušenosti, sílu a naději, že dovedou vyřešit svůj společný problém a pomoci ostatním k uzdravení z nutkavého přejídání."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Anonymní Přejídači" # add your company name
  github = "pospispa" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "O Nás"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Akce"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Kontakty a Setkání"
    weight = -100
    url = "/docs/kontakty-setkani/"
